version: "3.5"
services:
    nginx:
        container_name: asgard-nginx
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443

    db-mysql:
        container_name: asgard-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db_name
            MYSQL_USER: user_name
            MYSQL_PASSWORD: password

    heimdall:
        container_name: heimdall
        build: ./heimdall-remote-monitor
        image: treed1104/heimdall:latest
        restart: always
        links:
            - db-mysql
        ports:
            - 5000:5000

    mimir:
        container_name: mimir
        build: ./mimir-timetabling
        image: treed1104/mimir:latest
        restart: always
        links:
            - db-mysql
        ports:
            - 5100:5000
