version: "3.5"
networks:
    asgard-network:
        name: asgard-network
services:
    nginx:
        container_name: asgard-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./heimdall-remote-monitor/web/dist:/var/www/heimdall
            - ./mimir-timetabling/web/dist:/var/www/mimir
        ports:
            - 80:80
            - 443:443
        networks:
            - asgard-network

    db-mysql:
        container_name: asgard-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db_name
            MYSQL_USER: user_name
            MYSQL_PASSWORD: password
        networks:
            - asgard-network

    heimdall-api:
        container_name: heimdall-api
        build:
            context: ./heimdall-remote-monitor/api
            dockerfile: Dockerfile
        image: treed1104/heimdall-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    heimdall-frontend:
        container_name: heimdall-frontend
        image: node:latest
        volumes:
            - ./heimdall-remote-monitor/web:/app
        working_dir: /app
        links:
            - heimdall-api
        command: "bash -c 'npm install . && npm run build'"
        networks:
            - asgard-network

    mimir-api:
        container_name: mimir-api
        build:
            context: ./mimir-timetabling/api
            dockerfile: Dockerfile
        image: treed1104/mimir-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    mimir-frontend:
        container_name: mimir-frontend
        image: node:latest
        volumes:
            - ./mimir-timetabling/web:/app
        working_dir: /app
        links:
            - mimir-api
        command: "bash -c 'npm install . && npm run build'"
        networks:
            - asgard-network

    yggdrasil-api:
        container_name: yggdrasil-api
        build:
            context: ./yggdrasil-content-carousel/api
            dockerfile: Dockerfile
        image: treed1104/yggdrasil-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    yggdrasil-frontend:
        container_name: yggdrasil-frontend
        image: node:latest
        volumes:
            - ./yggdrasil-content-carousel/web:/app
        working_dir: /app
        links:
            - yggdrasil-api
        command: "bash -c 'npm install . && npm run build'"
        networks:
            - asgard-network
