version: "3.5"
services:
    nginx:
        container_name: asgard-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./heimdall-remote-monitor/web/dist:/var/www/heimdall
            - ./mimir-timetabling/web/dist:/var/www/mimir
        ports:
            - 80:80
            - 443:443

    db-mysql:
        container_name: asgard-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db_name
            MYSQL_USER: user_name
            MYSQL_PASSWORD: password

    heimdall-api:
        container_name: heimdall-api
        build: ./heimdall-remote-monitor/api
        image: treed1104/heimdall-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"

    heimdall-frontend:
        container_name: heimdall-frontend
        image: node:latest
        volumes:
            - ./heimdall-remote-monitor/web:/app
        working_dir: /app
        links:
            - heimdall-api
        command: "bash -c 'npm install . && npm run build'"

    mimir-api:
        container_name: mimir-api
        build: ./mimir-timetabling/api
        image: treed1104/mimir-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"

    mimir-frontend:
        container_name: mimir-frontend
        image: node:latest
        volumes:
            - ./mimir-timetabling/web:/app
        working_dir: /app
        links:
            - mimir-api
        command: "bash -c 'npm install . && npm run build'"
