version: "3.5"
networks:
    asgard-network:
        name: asgard-network
services:
    nginx:
        container_name: asgard-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        networks:
            - asgard-network

    db-mysql:
        container_name: asgard-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/test_db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pL3m6VursT7BEmn
            MYSQL_DATABASE: db_asgard
            MYSQL_USER: root
            MYSQL_PASSWORD: pL3m6VursT7BEmn
        networks:
            - asgard-network

    heimdall-api:
        container_name: heimdall-api
        build:
            context: ./heimdall-remote-monitor/api
            dockerfile: Dockerfile.dev
        image: treed1104/heimdall-api-dev:latest
        volumes:
            - ./heimdall-remote-monitor/api:/usr/src/app
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    heimdall-frontend:
        container_name: heimdall-frontend
        image: node:latest
        volumes:
            - ./heimdall-remote-monitor/web:/app
        working_dir: /app
        links:
            - heimdall-api
        expose:
            - "8080"
        command: "bash -c 'yarn && yarn run dev'"
        networks:
            - asgard-network

    mimir-api:
        container_name: mimir-api
        build:
            context: ./mimir-timetabling/api
            dockerfile: Dockerfile.dev
        image: treed1104/mimir-api-dev:latest
        volumes:
            - ./mimir-timetabling/api:/usr/src/app
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    mimir-frontend:
        container_name: mimir-frontend
        image: node:latest
        volumes:
            - ./mimir-timetabling/web:/app
        working_dir: /app
        links:
            - mimir-api
        expose:
            - "8080"
        command: "bash -c 'yarn && yarn run dev'"
        networks:
            - asgard-network

    yggdrasil-api:
        container_name: yggdrasil-api
        build:
            context: ./yggdrasil-content-carousel/api
            dockerfile: Dockerfile.dev
        image: treed1104/yggdrasil-api-dev:latest
        volumes:
            - ./yggdrasil-content-carousel/api:/usr/src/app
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - asgard-network

    yggdrasil-frontend:
        container_name: yggdrasil-frontend
        image: node:latest
        volumes:
            - ./yggdrasil-content-carousel/web:/app
        working_dir: /app
        links:
            - yggdrasil-api
        expose:
            - "8080"  
        command: "bash -c 'yarn && yarn run dev'"
        networks:
            - asgard-network
